In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

# Read the specified number of rows from the CSV file
df = pd.read_csv(r'C:\Users\pola_\OneDrive\Documents\Cesar\Data-bootcamp-UoT\Lessons\week 23\final project\Final_Project_Machine_Learning\Resources\US_Accidents_March23.csv')

df

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,Source2,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,0.010,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,Source2,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,NaN,NaN,0.010,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,Source2,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,NaN,NaN,0.010,...,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,Source2,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,NaN,NaN,0.010,...,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,Source2,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,NaN,NaN,0.010,...,False,False,False,False,True,False,Day,Day,Day,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7728389,A-7777757,Source1,2,2019-08-23 18:03:25,2019-08-23 18:32:01,34.002480,-117.379360,33.99888,-117.37094,0.543,...,False,False,False,False,False,False,Day,Day,Day,Day
7728390,A-7777758,Source1,2,2019-08-23 19:11:30,2019-08-23 19:38:23,32.766960,-117.148060,32.76555,-117.15363,0.338,...,False,False,False,False,False,False,Day,Day,Day,Day
7728391,A-7777759,Source1,2,2019-08-23 19:00:21,2019-08-23 19:28:49,33.775450,-117.847790,33.77740,-117.85727,0.561,...,False,False,False,False,False,False,Day,Day,Day,Day
7728392,A-7777760,Source1,2,2019-08-23 19:00:21,2019-08-23 19:29:42,33.992460,-118.403020,33.98311,-118.39565,0.772,...,False,False,False,False,False,False,Day,Day,Day,Day
7728393,A-7777761,Source1,2,2019-08-23 18:52:06,2019-08-23 19:21:31,34.133930,-117.230920,34.13736,-117.23934,0.537,...,False,False,False,False,False,False,Day,Day,Day,Day

In [2]:
# Print the information about the DataFrame including column names and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7728394 entries, 0 to 7728393
Data columns (total 46 columns):
 #   Column                 Dtype
---  ------                 -----
 0   ID                     object
 1   Source                 object
 2   Severity               int64
 3   Start_Time             object
 4   End_Time               object
 5   Start_Lat              float64
 6   Start_Lng              float64
 7   End_Lat                float64
 8   End_Lng                float64
 9   Distance(mi)           float64
 10  Description            object
 11  Street                 object
 12  City                   object
 13  County                 object
 14  State                  object
 15  Zipcode                object
 16  Country                object
 17  Timezone               object
 18  Airport_Code           object
 19  Weather_Timestamp      object
 20  Temperature(F)         float64
 21  Wind_Chill(F)          float64
 22  Humidity(%)            float64
 23  Pressure(in)           float64
 24  Visibility(mi)         float64
 25  Wind_Direction         object
 26  Wind_Speed(mph)        float64
 27  Precipitation(in)      float64
 28  Weather_Condition      object
 29  Amenity                bool
 30  Bump                   bool
 31  Crossing               bool
 32  Give_Way               bool
 33  Junction               bool
 34  No_Exit                bool
 35  Railway                bool
 36  Roundabout             bool
 37  Station                bool
 38  Stop                   bool
 39  Traffic_Calming        bool
 40  Traffic_Signal         bool
 41  Turning_Loop           bool
 42  Sunrise_Sunset         object
 43  Civil_Twilight         object
 44  Nautical_Twilight      object
 45  Astronomical_Twilight  object
dtypes: bool(13), float64(12), int64(1), object(20)
memory usage: 2.0+ GB

In [3]:
# Convert 'Start_Time' to datetime
df['Start_Time'] = pd.to_datetime(df['Start_Time'])

# Sort by 'Start_Time'
df.sort_values(by='Start_Time', inplace=True)

In [4]:
# Count the unique values in 'City'
city_counts = df['City'].value_counts()

# Calculate the total number of rows (to use for calculating proportions)
total_rows = len(df)

# Get the proportion of each 'City'
city_proportions = city_counts / total_rows

# proportions as percentages
city_percentages = city_proportions * 100

# print counts and proportions
print(city_counts)
print(city_proportions)

Miami          186917
Houston        169609
Los Angeles    156491
Charlotte      138652
Dallas         130939
                ...
Tingley             1
Swissvale           1
South Shore         1
Union Gap           1
Eleanor             1
Name: City, Length: 13678, dtype: int64
Miami          2.418575e-02
Houston        2.194622e-02
Los Angeles    2.024884e-02
Charlotte      1.794060e-02
Dallas         1.694259e-02
                   ...
Tingley        1.293930e-07
Swissvale      1.293930e-07
South Shore    1.293930e-07
Union Gap      1.293930e-07
Eleanor        1.293930e-07
Name: City, Length: 13678, dtype: float64

In [5]:
# Convert city_counts to a DataFrame
city_counts_df = city_counts.reset_index()
city_counts_df.columns = ['City', 'Count']  

# Calculate proportions and add as a new column
city_counts_df['Proportion'] = city_counts_df['Count'] / city_counts_df['Count'].sum()

# Save the DataFrame to a CSV file
output_path = r'C:\Users\pola_\OneDrive\Documents\Cesar\Data-bootcamp-UoT\Lessons\week 23\final project\Final_Project_Machine_Learning\Resources\city_counts.csv'
city_counts_df.to_csv(output_path, index=False)

In [7]:
# Sample 50% of the data randomly
sampled_df = df.sample(frac=0.5, random_state=1)

# Save the sampled DataFrame to a CSV file For the EDA in Tableau
sampled_output_path = r'C:\Users\pola_\OneDrive\Documents\Cesar\Data-bootcamp-UoT\Lessons\week 23\final project\Final_Project_Machine_Learning\Resources\sampled_US_Accidents.csv'
sampled_df.to_csv(sampled_output_path, index=False)

In [8]:
# calculate the city counts and proportions for the sampled data
sampled_city_counts = sampled_df['City'].value_counts()

# Convert sampled city_counts to a DataFrame
sampled_city_counts_df = sampled_city_counts.reset_index()
sampled_city_counts_df.columns = ['City', 'Sampled_Count']  

# Calculate proportions for the sampled data and add as a new column
sampled_city_counts_df['Sampled_Proportion'] = sampled_city_counts_df['Sampled_Count'] / sampled_city_counts_df['Sampled_Count'].sum()

# Save the sampled city counts DataFrame to a CSV file
sampled_city_counts_output_path = r'C:\Users\pola_\OneDrive\Documents\Cesar\Data-bootcamp-UoT\Lessons\week 23\final project\Final_Project_Machine_Learning\Resources\sampled_city_counts.csv'
sampled_city_counts_df.to_csv(sampled_city_counts_output_path, index=False)

In [9]:
# Load the original city counts CSV file
original_city_counts_path = r'C:\Users\pola_\OneDrive\Documents\Cesar\Data-bootcamp-UoT\Lessons\week 23\final project\Final_Project_Machine_Learning\Resources\city_counts.csv'
original_city_counts_df = pd.read_csv(original_city_counts_path)

# Load the sampled city counts CSV file
sampled_city_counts_path = r'C:\Users\pola_\OneDrive\Documents\Cesar\Data-bootcamp-UoT\Lessons\week 23\final project\Final_Project_Machine_Learning\Resources\sampled_city_counts.csv'
sampled_city_counts_df = pd.read_csv(sampled_city_counts_path)

# Ensure the column names are correct
print(original_city_counts_df.columns)
print(sampled_city_counts_df.columns)

Index(['City', 'Count', 'Proportion'], dtype='object')
Index(['City', 'Sampled_Count', 'Sampled_Proportion'], dtype='object')

In [10]:
comparison_df = pd.merge(original_city_counts_df, sampled_city_counts_df, on='City', how='outer')

# Calculate the absolute and relative differences in counts and proportions
comparison_df['Count_Difference'] = comparison_df['Count'] - comparison_df['Sampled_Count']
comparison_df['Proportion_Difference'] = comparison_df['Proportion'] - comparison_df['Sampled_Proportion']

# export  comparison to a CSV file
comparison_output_path = r'C:\Users\pola_\OneDrive\Documents\Cesar\Data-bootcamp-UoT\Lessons\week 23\final project\Final_Project_Machine_Learning\Resources\city_counts_comparison.csv'
comparison_df.to_csv(comparison_output_path, index=False)

In [11]:
# Find the maximum count difference
max_difference_index = comparison_df['Count_Difference'].idxmax()

# Print the row with the max count difference
max_difference_city = comparison_df.loc[max_difference_index]

print(max_difference_city)

City                        Miami
Count                      186917
Proportion               0.024187
Sampled_Count             93408.0
Sampled_Proportion       0.024173
Count_Difference          93509.0
Proportion_Difference    0.000013
Name: 0, dtype: object

# We can use the new file 'sampled_US_Accidents' which shows a good representation by city of the original file.  The sampled file is 50% of the original file, mantaining a proper representaation of the original, and it allows to properly run the analysis in Tableau and Python.

In [4]:
import pandas as pd

# Read the updated file for more cleaning
sampled_df = pd.read_csv(r'C:\Users\pola_\OneDrive\Documents\Cesar\Data-bootcamp-UoT\Lessons\week 23\final project\Final_Project_Machine_Learning\Resources\sampled_US_Accidents.csv')

sampled_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3864197 entries, 0 to 3864196
Data columns (total 46 columns):
 #   Column                 Dtype
---  ------                 -----
 0   ID                     object
 1   Source                 object
 2   Severity               int64
 3   Start_Time             object
 4   End_Time               object
 5   Start_Lat              float64
 6   Start_Lng              float64
 7   End_Lat                float64
 8   End_Lng                float64
 9   Distance(mi)           float64
 10  Description            object
 11  Street                 object
 12  City                   object
 13  County                 object
 14  State                  object
 15  Zipcode                object
 16  Country                object
 17  Timezone               object
 18  Airport_Code           object
 19  Weather_Timestamp      object
 20  Temperature(F)         float64
 21  Wind_Chill(F)          float64
 22  Humidity(%)            float64
 23  Pressure(in)           float64
 24  Visibility(mi)         float64
 25  Wind_Direction         object
 26  Wind_Speed(mph)        float64
 27  Precipitation(in)      float64
 28  Weather_Condition      object
 29  Amenity                bool
 30  Bump                   bool
 31  Crossing               bool
 32  Give_Way               bool
 33  Junction               bool
 34  No_Exit                bool
 35  Railway                bool
 36  Roundabout             bool
 37  Station                bool
 38  Stop                   bool
 39  Traffic_Calming        bool
 40  Traffic_Signal         bool
 41  Turning_Loop           bool
 42  Sunrise_Sunset         object
 43  Civil_Twilight         object
 44  Nautical_Twilight      object
 45  Astronomical_Twilight  object
dtypes: bool(13), float64(12), int64(1), object(20)
memory usage: 1020.8+ MB

## Additional data cleaning.

In [5]:
# Check for missing values in each column
missing_values = sampled_df.isnull().sum()

# Print the count of missing values for each column
print(missing_values)

ID                             0
Source                         0
Severity                       0
Start_Time                     0
End_Time                       0
Start_Lat                      0
Start_Lng                      0
End_Lat                  1700697
End_Lng                  1700697
Distance(mi)                   0
Description                    3
Street                      5372
City                         111
County                         0
State                          0
Zipcode                      933
Country                        0
Timezone                    3911
Airport_Code               11331
Weather_Timestamp          60158
Temperature(F)             81817
Wind_Chill(F)             998957
Humidity(%)                86994
Pressure(in)               70442
Visibility(mi)             88620
Wind_Direction             87734
Wind_Speed(mph)           285828
Precipitation(in)        1101752
Weather_Condition          86783
Amenity                        0
Bump                           0
Crossing                       0
Give_Way                       0
Junction                       0
No_Exit                        0
Railway                        0
Roundabout                     0
Station                        0
Stop                           0
Traffic_Calming                0
Traffic_Signal                 0
Turning_Loop                   0
Sunrise_Sunset             11662
Civil_Twilight             11662
Nautical_Twilight          11662
Astronomical_Twilight      11662
dtype: int64

In [6]:
# Columns to drop
columns_to_drop = [
    'End_Lat', 'End_Lng', 'Street', 'City', 'Airport_Code', 
    'Weather_Timestamp', 'Wind_Chill(F)', 'Wind_Direction', 
    'Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight',
    'Description', 'Timezone', 'Zipcode'
]

# Drop the columns
clean_sampled_df = sampled_df.drop(columns=columns_to_drop)

# Check the DataFrame to ensure the columns have been dropped
clean_sampled_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3864197 entries, 0 to 3864196
Data columns (total 32 columns):
 #   Column                 Dtype
---  ------                 -----
 0   ID                     object
 1   Source                 object
 2   Severity               int64
 3   Start_Time             object
 4   End_Time               object
 5   Start_Lat              float64
 6   Start_Lng              float64
 7   Distance(mi)           float64
 8   County                 object
 9   State                  object
 10  Country                object
 11  Temperature(F)         float64
 12  Humidity(%)            float64
 13  Pressure(in)           float64
 14  Visibility(mi)         float64
 15  Wind_Speed(mph)        float64
 16  Precipitation(in)      float64
 17  Weather_Condition      object
 18  Amenity                bool
 19  Bump                   bool
 20  Crossing               bool
 21  Give_Way               bool
 22  Junction               bool
 23  No_Exit                bool
 24  Railway                bool
 25  Roundabout             bool
 26  Station                bool
 27  Stop                   bool
 28  Traffic_Calming        bool
 29  Traffic_Signal         bool
 30  Turning_Loop           bool
 31  Astronomical_Twilight  object
dtypes: bool(13), float64(9), int64(1), object(9)
memory usage: 608.1+ MB

In [7]:
# Check for missing values in each column
missing_values = clean_sampled_df.isnull().sum()

# Print the count of missing values for each column
print(missing_values)

ID                             0
Source                         0
Severity                       0
Start_Time                     0
End_Time                       0
Start_Lat                      0
Start_Lng                      0
Distance(mi)                   0
County                         0
State                          0
Country                        0
Temperature(F)             81817
Humidity(%)                86994
Pressure(in)               70442
Visibility(mi)             88620
Wind_Speed(mph)           285828
Precipitation(in)        1101752
Weather_Condition          86783
Amenity                        0
Bump                           0
Crossing                       0
Give_Way                       0
Junction                       0
No_Exit                        0
Railway                        0
Roundabout                     0
Station                        0
Stop                           0
Traffic_Calming                0
Traffic_Signal                 0
Turning_Loop                   0
Astronomical_Twilight      11662
dtype: int64

In [8]:
# Fill missing values for numerical columns with their mean
numerical_columns = ['Temperature(F)', 'Humidity(%)', 'Pressure(in)', 'Visibility(mi)', 'Wind_Speed(mph)', 'Precipitation(in)']
for column in numerical_columns:
    clean_sampled_df[column].fillna(clean_sampled_df[column].mean(), inplace=True)

# Fill missing values for 'Weather_Condition' and 'Astronomical_Twilight' with 'NA'
clean_sampled_df['Weather_Condition'].fillna('NA', inplace=True)
clean_sampled_df['Astronomical_Twilight'].fillna('NA', inplace=True)

# Verify the changes
print(clean_sampled_df.isnull().sum())

ID                       0
Source                   0
Severity                 0
Start_Time               0
End_Time                 0
Start_Lat                0
Start_Lng                0
Distance(mi)             0
County                   0
State                    0
Country                  0
Temperature(F)           0
Humidity(%)              0
Pressure(in)             0
Visibility(mi)           0
Wind_Speed(mph)          0
Precipitation(in)        0
Weather_Condition        0
Amenity                  0
Bump                     0
Crossing                 0
Give_Way                 0
Junction                 0
No_Exit                  0
Railway                  0
Roundabout               0
Station                  0
Stop                     0
Traffic_Calming          0
Traffic_Signal           0
Turning_Loop             0
Astronomical_Twilight    0
dtype: int64

In [9]:
#export clean dataframe to a CSV file
clean_sampled_df_path = r'C:\Users\pola_\OneDrive\Documents\Cesar\Data-bootcamp-UoT\Lessons\week 23\final project\Final_Project_Machine_Learning\Resources\clean_sampled_US_Accidents.csv'
clean_sampled_df.to_csv(clean_sampled_df_path, index=False)

In [10]:
# Ensure 'Start_Time' is a datetime type if not already converted
clean_sampled_df['Start_Time'] = pd.to_datetime(clean_sampled_df['Start_Time'])

# Extract Year, Month, Day of the Week, and Time
clean_sampled_df['Year'] = clean_sampled_df['Start_Time'].dt.year
clean_sampled_df['Month'] = clean_sampled_df['Start_Time'].dt.month
clean_sampled_df['DayOfWeek'] = clean_sampled_df['Start_Time'].dt.dayofweek  # Monday=0, Sunday=6
clean_sampled_df['Time'] = clean_sampled_df['Start_Time'].dt.time

# Check the first few rows to confirm the changes
print(clean_sampled_df[['Start_Time', 'Year', 'Month', 'DayOfWeek', 'Time']].head())

           Start_Time  Year  Month  DayOfWeek      Time
0 2020-11-03 00:54:07  2020     11          1  00:54:07
1 2020-07-08 13:09:55  2020      7          2  13:09:55
2 2022-05-18 17:18:44  2022      5          2  17:18:44
3 2021-01-26 05:01:29  2021      1          1  05:01:29
4 2017-01-12 14:03:42  2017      1          3  14:03:42

In [11]:
# Columns to drop
columns_to_drop = ['Source', 'End_Time', 'Country']

# Drop the columns
clean_sampled_df.drop(columns=columns_to_drop, inplace=True)

# Check the DataFrame to ensure the columns have been dropped
print(clean_sampled_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3864197 entries, 0 to 3864196
Data columns (total 33 columns):
 #   Column                 Dtype
---  ------                 -----
 0   ID                     object
 1   Severity               int64
 2   Start_Time             datetime64[ns]
 3   Start_Lat              float64
 4   Start_Lng              float64
 5   Distance(mi)           float64
 6   County                 object
 7   State                  object
 8   Temperature(F)         float64
 9   Humidity(%)            float64
 10  Pressure(in)           float64
 11  Visibility(mi)         float64
 12  Wind_Speed(mph)        float64
 13  Precipitation(in)      float64
 14  Weather_Condition      object
 15  Amenity                bool
 16  Bump                   bool
 17  Crossing               bool
 18  Give_Way               bool
 19  Junction               bool
 20  No_Exit                bool
 21  Railway                bool
 22  Roundabout             bool
 23  Station                bool
 24  Stop                   bool
 25  Traffic_Calming        bool
 26  Traffic_Signal         bool
 27  Turning_Loop           bool
 28  Astronomical_Twilight  object
 29  Year                   int64
 30  Month                  int64
 31  DayOfWeek              int64
 32  Time                   object
dtypes: bool(13), datetime64[ns](1), float64(9), int64(4), object(6)
memory usage: 637.5+ MB
None

In [12]:
# Determine the number of unique values in each column.
unique_values = clean_sampled_df.nunique()
print(unique_values)

ID                       3864197
Severity                       4
Start_Time               3209744
Start_Lat                1625808
Start_Lng                1651774
Distance(mi)               18733
County                      1824
State                         49
Temperature(F)               831
Humidity(%)                  101
Pressure(in)                1111
Visibility(mi)                86
Wind_Speed(mph)              157
Precipitation(in)            264
Weather_Condition            136
Amenity                        2
Bump                           2
Crossing                       2
Give_Way                       2
Junction                       2
No_Exit                        2
Railway                        2
Roundabout                     2
Station                        2
Stop                           2
Traffic_Calming                2
Traffic_Signal                 2
Turning_Loop                   1
Astronomical_Twilight          3
Year                           8
Month                         12
DayOfWeek                      7
Time                       86371
dtype: int64

In [13]:
# Filter out rows with the year 2016 or 2023
clean_sampled_df = clean_sampled_df[(clean_sampled_df['Year'] != 2016) & (clean_sampled_df['Year'] != 2023)]

In [14]:
# Set option to display all rows
pd.set_option('display.max_rows', None)

# Get the counts of unique values in 'Weather_Condition'
weather_condition_counts = clean_sampled_df['Weather_Condition'].value_counts()

# Display the weather conditions and their counts
print(weather_condition_counts)

Fair                                   1231285
Mostly Cloudy                           467964
Cloudy                                  384053
Partly Cloudy                           320925
Clear                                   317206
Overcast                                163017
Light Rain                              161543
Scattered Clouds                         82298
NA                                       79210
Light Snow                               56983
Fog                                      46313
Rain                                     38141
Haze                                     35274
Fair / Windy                             16884
Heavy Rain                               14968
Light Drizzle                            10505
Thunder in the Vicinity                   8724
T-Storm                                   8203
Cloudy / Windy                            7834
Mostly Cloudy / Windy                     7740
Thunder                                   6985
Snow                                      6853
Light Rain with Thunder                   6658
Smoke                                     6150
Wintry Mix                                4926
Heavy T-Storm                             4733
Partly Cloudy / Windy                     4711
Light Rain / Windy                        3789
Light Snow / Windy                        3071
Drizzle                                   2180
Heavy Snow                                2067
Light Thunderstorms and Rain              1991
Patches of Fog                            1923
Thunderstorm                              1803
Mist                                      1633
Light Freezing Rain                       1585
N/A Precipitation                         1471
Shallow Fog                               1455
Rain / Windy                              1094
Heavy Thunderstorms and Rain              1072
Thunderstorms and Rain                     945
Haze / Windy                               755
Heavy Rain / Windy                         729
Showers in the Vicinity                    709
Snow / Windy                               624
Light Freezing Drizzle                     531
Heavy T-Storm / Windy                      529
Light Freezing Fog                         461
Blowing Snow / Windy                       417
Heavy Snow / Windy                         412
Blowing Snow                               366
T-Storm / Windy                            366
Fog / Windy                                325
Thunder / Windy                            267
Drizzle and Fog                            197
Heavy Drizzle                              195
Wintry Mix / Windy                         154
Snow and Sleet                             153
Blowing Dust / Windy                       124
Light Ice Pellets                          124
Light Rain Shower                          121
Light Drizzle / Windy                      113
Light Sleet                                100
Blowing Dust                                96
Widespread Dust                             87
Freezing Rain                               84
Light Snow and Sleet                        82
Sleet                                       72
Light Rain Showers                          70
Rain Showers                                50
Ice Pellets                                 48
Smoke / Windy                               41
Light Freezing Rain / Windy                 39
Snow and Sleet / Windy                      36
Small Hail                                  31
Rain Shower                                 27
Light Snow Shower                           27
Sand / Dust Whirlwinds                      26
Light Snow and Sleet / Windy                24
Squalls / Windy                             23
Squalls                                     19
Freezing Drizzle                            16
Partial Fog                                 16
Widespread Dust / Windy                     15
Volcanic Ash                                13
Light Snow with Thunder                     13
Sand                                        12
Light Snow Showers                          12
Hail                                        11
Thunder and Hail                            10
Tornado                                     10
Heavy Sleet                                  9
Light Rain Shower / Windy                    9
Thunder / Wintry Mix                         9
Light Thunderstorms and Snow                 9
Snow and Thunder                             9
Funnel Cloud                                 8
Drizzle / Windy                              8
Light Sleet / Windy                          7
Heavy Freezing Rain                          7
Heavy Rain Showers                           6
Light Haze                                   6
Drifting Snow / Windy                        5
Heavy Thunderstorms with Small Hail          4
Shallow Fog / Windy                          4
Thunder / Wintry Mix / Windy                 4
Light Snow Grains                            4
Snow Grains                                  3
Heavy Ice Pellets                            3
Patches of Fog / Windy                       3
Sleet and Thunder                            3
Thunderstorms and Snow                       3
Heavy Snow with Thunder                      3
Light Hail                                   2
Snow Showers                                 2
Heavy Freezing Drizzle                       2
Light Blowing Snow                           2
Rain and Sleet                               2
Sand / Dust Whirls Nearby                    2
Heavy Blowing Snow                           2
Duststorm                                    2
Partial Fog / Windy                          1
Light Fog                                    1
Mist / Windy                                 1
Snow and Thunder / Windy                     1
Heavy Freezing Rain / Windy                  1
Heavy Sleet and Thunder                      1
Heavy Rain Shower                            1
Sand / Dust Whirlwinds / Windy               1
Drifting Snow                                1
Heavy Thunderstorms and Snow                 1
Freezing Rain / Windy                        1
Light Thunderstorm                           1
Name: Weather_Condition, dtype: int64

In [15]:
# Create a mapping dictionary for the new weather condition groups
weather_mapping = {
    'Fair / Windy': 'Fair',
    'Mostly Cloudy': 'Cloudy',
    'Cloudy / Windy': 'Cloudy',
    'Mostly Cloudy / Windy': 'Cloudy',
    'Overcast': 'Cloudy',
    'Partly Cloudy / Windy': 'Partly Cloudy',
    'Scattered Clouds': 'Partly Cloudy',
    'Light Snow': 'Snow',
    'Light Snow / Windy': 'Snow',
    'Snow / Windy': 'Snow',
    'Heavy Snow / Windy': 'Snow',
    'Snow and Sleet': 'Snow',
    'Snow and Sleet / Windy': 'Snow',
    'Light Snow and Sleet / Windy': 'Snow',
    'Light Snow Showers': 'Snow',
    'Snow and Thunder': 'Snow',
    'Light Snow Grains': 'Snow',
    'Thunderstorms and Snow': 'Snow',
    'Snow Showers': 'Snow',
    'Heavy Blowing Snow': 'Snow',
    'Drifting Snow': 'Snow',
    'Heavy Snow': 'Snow',
    'Blowing Snow / Windy': 'Snow',
    'Blowing Snow': 'Snow',
    'Light Snow and Sleet': 'Snow',
    'Light Snow Shower': 'Snow',
    'Light Snow with Thunder': 'Snow',
    'Light Thunderstorms and Snow': 'Snow',
    'Drifting Snow / Windy': 'Snow',
    'Snow Grains': 'Snow',
    'Heavy Snow with Thunder': 'Snow',
    'Light Blowing Snow': 'Snow',
    'Snow and Thunder / Windy': 'Snow',
    'Heavy Thunderstorms and Snow': 'Snow',
    'Patches of Fog': 'Fog',
    'Light Freezing Fog': 'Fog',
    'Drizzle and Fog': 'Fog',
    'Shallow Fog / Windy': 'Fog',
    'Partial Fog / Windy': 'Fog',
    'Shallow Fog': 'Fog',
    'Fog / Windy': 'Fog',
    'Partial Fog': 'Fog',
    'Patches of Fog / Windy': 'Fog',
    'Light Fog': 'Fog',
    'Rain / Windy': 'Rain',
    'Rain Shower': 'Rain',
    'Showers in the Vicinity': 'Rain',
    'Rain Showers': 'Rain',
    'N/A Precipitation': 'Rain',
    'Heavy Rain': 'Rain',
    'Heavy Rain / Windy': 'Rain',
    'Heavy Rain Shower': 'Rain',
    'Heavy Rain Showers': 'Rain',
    'Light Rain with Thunder': 'Rain',
    'Light Rain': 'Rain',
    'Light Thunderstorms and Rain': 'Rain',
    'Light Rain Showers': 'Rain',
    'Light Drizzle': 'Rain',
    'Light Rain / Windy': 'Rain',
    'Light Rain Shower': 'Rain',
    'Light Rain Shower / Windy': 'Rain',
    'Haze': 'Haze/Smoke/Dust',
    'Haze / Windy': 'Haze/Smoke/Dust',
    'Blowing Dust / Windy': 'Haze/Smoke/Dust',
    'Smoke / Windy': 'Haze/Smoke/Dust',
    'Sand': 'Haze/Smoke/Dust',
    'Sand / Dust Whirls Nearby': 'Haze/Smoke/Dust',
    'Sand / Dust Whirlwinds / Windy': 'Haze/Smoke/Dust',
    'Volcanic Ash': 'Haze/Smoke/Dust',
    'Smoke': 'Haze/Smoke/Dust',
    'Widespread Dust': 'Haze/Smoke/Dust',
    'Blowing Dust': 'Haze/Smoke/Dust',
    'Widespread Dust / Windy': 'Haze/Smoke/Dust',
    'Light Haze': 'Haze/Smoke/Dust',
    'Duststorm': 'Haze/Smoke/Dust',
    'Sand / Dust Whirlwinds': 'Haze/Smoke/Dust',
    'Thunder in the Vicinity': 'Thunderstorm',
    'Thunderstorms and Rain': 'Thunderstorm',
    'T-Storm / Windy': 'Thunderstorm',
    'Thunder and Hail': 'Thunderstorm',
    'Squalls / Windy': 'Thunderstorm',
    'T-Storm': 'Thunderstorm',
    'Heavy Thunderstorms and Rain': 'Thunderstorm',
    'Heavy T-Storm / Windy': 'Thunderstorm',
    'Thunder / Windy': 'Thunderstorm',
    'Light Thunderstorm': 'Thunderstorm',
    'Squalls': 'Thunderstorm',
    'Thunder': 'Thunderstorm',
    'Heavy T-Storm': 'Thunderstorm',
    'Thunder / Wintry Mix / Windy': 'Wintry Mix',
    'Sleet and Thunder': 'Wintry Mix',
    'Heavy Sleet and Thunder': 'Wintry Mix',
    'Light Sleet': 'Wintry Mix',
    'Ice Pellets': 'Wintry Mix',
    'Hail': 'Wintry Mix',
    'Light Freezing Rain': 'Wintry Mix',
    'Freezing Rain': 'Wintry Mix',
    'Freezing Drizzle': 'Wintry Mix',
    'Heavy Freezing Drizzle': 'Wintry Mix',
    'Heavy Sleet': 'Wintry Mix',
    'Thunder / Wintry Mix': 'Wintry Mix',
    'Wintry Mix / Windy': 'Wintry Mix',
    'Heavy Ice Pellets': 'Wintry Mix',
    'Light Hail': 'Wintry Mix',
    'Light Ice Pellets': 'Wintry Mix',
    'Sleet': 'Wintry Mix',
    'Small Hail': 'Wintry Mix',
    'Light Sleet / Windy': 'Wintry Mix',
    'Rain and Sleet': 'Wintry Mix',
    'Light Freezing Drizzle': 'Wintry Mix',
    'Light Freezing Rain / Windy': 'Wintry Mix',
    'Heavy Freezing Rain': 'Wintry Mix',
    'Heavy Freezing Rain / Windy': 'Wintry Mix',
    'Heavy Thunderstorms with Small Hail': 'Wintry Mix',
    'Freezing Rain / Windy': 'Wintry Mix',
    'Light Drizzle / Windy': 'Drizzle',
    'Heavy Drizzle': 'Drizzle',
    'Drizzle / Windy': 'Drizzle',
    'Mist / Windy': 'Mist',
    'Funnel Cloud': 'Tornado',
  
}

# Replace the weather conditions in the DataFrame with the new groups
clean_sampled_df['Weather_Condition'] = clean_sampled_df['Weather_Condition'].replace(weather_mapping)

# Verify the changes by checking the counts of the new weather condition groups
print(clean_sampled_df['Weather_Condition'].value_counts())

Fair               1248169
Cloudy             1030608
Partly Cloudy       407934
Clear               317206
Rain                241882
NA                   79210
Snow                 71185
Fog                  50699
Haze/Smoke/Dust      42604
Thunderstorm         33680
Wintry Mix            7776
Drizzle               2496
Mist                  1634
Tornado                 18
Name: Weather_Condition, dtype: int64

In [16]:
clean_sampled_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3535101 entries, 0 to 3864196
Data columns (total 33 columns):
 #   Column                 Dtype
---  ------                 -----
 0   ID                     object
 1   Severity               int64
 2   Start_Time             datetime64[ns]
 3   Start_Lat              float64
 4   Start_Lng              float64
 5   Distance(mi)           float64
 6   County                 object
 7   State                  object
 8   Temperature(F)         float64
 9   Humidity(%)            float64
 10  Pressure(in)           float64
 11  Visibility(mi)         float64
 12  Wind_Speed(mph)        float64
 13  Precipitation(in)      float64
 14  Weather_Condition      object
 15  Amenity                bool
 16  Bump                   bool
 17  Crossing               bool
 18  Give_Way               bool
 19  Junction               bool
 20  No_Exit                bool
 21  Railway                bool
 22  Roundabout             bool
 23  Station                bool
 24  Stop                   bool
 25  Traffic_Calming        bool
 26  Traffic_Signal         bool
 27  Turning_Loop           bool
 28  Astronomical_Twilight  object
 29  Year                   int64
 30  Month                  int64
 31  DayOfWeek              int64
 32  Time                   object
dtypes: bool(13), datetime64[ns](1), float64(9), int64(4), object(6)
memory usage: 610.2+ MB

In [17]:
#export clean dataframe to a CSV file
clean_sampled_df_path = r'C:\Users\pola_\OneDrive\Documents\Cesar\Data-bootcamp-UoT\Lessons\week 23\final project\Final_Project_Machine_Learning\Resources\clean_sampled_US_Accidents_for_model.csv'
clean_sampled_df.to_csv(clean_sampled_df_path, index=False)